# Generated by Django 4.2.7 on 2023-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_product_image_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('classified', 'Classified'), ('on_sale', 'On Sale'), ('sold', 'Sold')], max_length=20)),
            ],
        ),
    ]
