# Generated by Django 4.2.7 on 2023-11-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_testproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('acquired', 'Acquired'), ('classified', 'Classified'), ('on_sale', 'On Sale'), ('sold', 'Sold')], default='acquired', max_length=20),
        ),
    ]
