# Generated by Django 4.2.7 on 2023-11-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='uncategorized', max_length=50),
        ),
    ]
